//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FileBinaryTransferSoap")]
    public interface FileBinaryTransferSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 buff 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFile", ReplyAction="*")]
        TestWebService.ServiceReference1.SaveFileResponse SaveFile(TestWebService.ServiceReference1.SaveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFile", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReference1.SaveFileResponse> SaveFileAsync(TestWebService.ServiceReference1.SaveFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWechatMessage", ReplyAction="*")]
        TestWebService.ServiceReference1.SendWechatMessageResponse SendWechatMessage(TestWebService.ServiceReference1.SendWechatMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWechatMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReference1.SendWechatMessageResponse> SendWechatMessageAsync(TestWebService.ServiceReference1.SendWechatMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFile", Namespace="http://tempuri.org/", Order=0)]
        public TestWebService.ServiceReference1.SaveFileRequestBody Body;
        
        public SaveFileRequest() {
        }
        
        public SaveFileRequest(TestWebService.ServiceReference1.SaveFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] buff;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TestWebService.ServiceReference1.ArrayOfString LstPhones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SubmitPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AfterPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FormKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string remindType;
        
        public SaveFileRequestBody() {
        }
        
        public SaveFileRequestBody(byte[] buff, string fileName, TestWebService.ServiceReference1.ArrayOfString LstPhones, string Content, string SubmitPhone, string AfterPhone, string FormKey, string remindType) {
            this.buff = buff;
            this.fileName = fileName;
            this.LstPhones = LstPhones;
            this.Content = Content;
            this.SubmitPhone = SubmitPhone;
            this.AfterPhone = AfterPhone;
            this.FormKey = FormKey;
            this.remindType = remindType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWebService.ServiceReference1.SaveFileResponseBody Body;
        
        public SaveFileResponse() {
        }
        
        public SaveFileResponse(TestWebService.ServiceReference1.SaveFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveFileResult;
        
        public SaveFileResponseBody() {
        }
        
        public SaveFileResponseBody(string SaveFileResult) {
            this.SaveFileResult = SaveFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWechatMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWechatMessage", Namespace="http://tempuri.org/", Order=0)]
        public TestWebService.ServiceReference1.SendWechatMessageRequestBody Body;
        
        public SendWechatMessageRequest() {
        }
        
        public SendWechatMessageRequest(TestWebService.ServiceReference1.SendWechatMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWechatMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public SendWechatMessageRequestBody() {
        }
        
        public SendWechatMessageRequestBody(string token, string mobile, string message) {
            this.token = token;
            this.mobile = mobile;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWechatMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWechatMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWebService.ServiceReference1.SendWechatMessageResponseBody Body;
        
        public SendWechatMessageResponse() {
        }
        
        public SendWechatMessageResponse(TestWebService.ServiceReference1.SendWechatMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWechatMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWechatMessageResult;
        
        public SendWechatMessageResponseBody() {
        }
        
        public SendWechatMessageResponseBody(string SendWechatMessageResult) {
            this.SendWechatMessageResult = SendWechatMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileBinaryTransferSoapChannel : TestWebService.ServiceReference1.FileBinaryTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileBinaryTransferSoapClient : System.ServiceModel.ClientBase<TestWebService.ServiceReference1.FileBinaryTransferSoap>, TestWebService.ServiceReference1.FileBinaryTransferSoap {
        
        public FileBinaryTransferSoapClient() {
        }
        
        public FileBinaryTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileBinaryTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileBinaryTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileBinaryTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReference1.SaveFileResponse TestWebService.ServiceReference1.FileBinaryTransferSoap.SaveFile(TestWebService.ServiceReference1.SaveFileRequest request) {
            return base.Channel.SaveFile(request);
        }
        
        public string SaveFile(byte[] buff, string fileName, TestWebService.ServiceReference1.ArrayOfString LstPhones, string Content, string SubmitPhone, string AfterPhone, string FormKey, string remindType) {
            TestWebService.ServiceReference1.SaveFileRequest inValue = new TestWebService.ServiceReference1.SaveFileRequest();
            inValue.Body = new TestWebService.ServiceReference1.SaveFileRequestBody();
            inValue.Body.buff = buff;
            inValue.Body.fileName = fileName;
            inValue.Body.LstPhones = LstPhones;
            inValue.Body.Content = Content;
            inValue.Body.SubmitPhone = SubmitPhone;
            inValue.Body.AfterPhone = AfterPhone;
            inValue.Body.FormKey = FormKey;
            inValue.Body.remindType = remindType;
            TestWebService.ServiceReference1.SaveFileResponse retVal = ((TestWebService.ServiceReference1.FileBinaryTransferSoap)(this)).SaveFile(inValue);
            return retVal.Body.SaveFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReference1.SaveFileResponse> TestWebService.ServiceReference1.FileBinaryTransferSoap.SaveFileAsync(TestWebService.ServiceReference1.SaveFileRequest request) {
            return base.Channel.SaveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReference1.SaveFileResponse> SaveFileAsync(byte[] buff, string fileName, TestWebService.ServiceReference1.ArrayOfString LstPhones, string Content, string SubmitPhone, string AfterPhone, string FormKey, string remindType) {
            TestWebService.ServiceReference1.SaveFileRequest inValue = new TestWebService.ServiceReference1.SaveFileRequest();
            inValue.Body = new TestWebService.ServiceReference1.SaveFileRequestBody();
            inValue.Body.buff = buff;
            inValue.Body.fileName = fileName;
            inValue.Body.LstPhones = LstPhones;
            inValue.Body.Content = Content;
            inValue.Body.SubmitPhone = SubmitPhone;
            inValue.Body.AfterPhone = AfterPhone;
            inValue.Body.FormKey = FormKey;
            inValue.Body.remindType = remindType;
            return ((TestWebService.ServiceReference1.FileBinaryTransferSoap)(this)).SaveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReference1.SendWechatMessageResponse TestWebService.ServiceReference1.FileBinaryTransferSoap.SendWechatMessage(TestWebService.ServiceReference1.SendWechatMessageRequest request) {
            return base.Channel.SendWechatMessage(request);
        }
        
        public string SendWechatMessage(string token, string mobile, string message) {
            TestWebService.ServiceReference1.SendWechatMessageRequest inValue = new TestWebService.ServiceReference1.SendWechatMessageRequest();
            inValue.Body = new TestWebService.ServiceReference1.SendWechatMessageRequestBody();
            inValue.Body.token = token;
            inValue.Body.mobile = mobile;
            inValue.Body.message = message;
            TestWebService.ServiceReference1.SendWechatMessageResponse retVal = ((TestWebService.ServiceReference1.FileBinaryTransferSoap)(this)).SendWechatMessage(inValue);
            return retVal.Body.SendWechatMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReference1.SendWechatMessageResponse> TestWebService.ServiceReference1.FileBinaryTransferSoap.SendWechatMessageAsync(TestWebService.ServiceReference1.SendWechatMessageRequest request) {
            return base.Channel.SendWechatMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReference1.SendWechatMessageResponse> SendWechatMessageAsync(string token, string mobile, string message) {
            TestWebService.ServiceReference1.SendWechatMessageRequest inValue = new TestWebService.ServiceReference1.SendWechatMessageRequest();
            inValue.Body = new TestWebService.ServiceReference1.SendWechatMessageRequestBody();
            inValue.Body.token = token;
            inValue.Body.mobile = mobile;
            inValue.Body.message = message;
            return ((TestWebService.ServiceReference1.FileBinaryTransferSoap)(this)).SendWechatMessageAsync(inValue);
        }
    }
}
